title: "Christmas Card 2025"
description: "Rae and Landon's 2025 Christmas Card"
# remote_theme: pages-themes/cayman@v0.2.0
remote_them: https://github.com/pages-themes/cayman.git
plugins:
- jekyll-remote-theme
